I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\nbij\\chpt1\\Projects\\NBIJ\\game\\saves\\navigation.json.new' -> 'E:\\nbij\\chpt1\\Projects\\NBIJ\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\main.py", line 610, in main
    renpy.dump.dump(False)
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\nbij\\chpt1\\Projects\\NBIJ\\game\\saves\\navigation.json.new' -> 'E:\\nbij\\chpt1\\Projects\\NBIJ\\game\\saves\\navigation.json'

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
 0.2
Thu May 11 22:08:50 2023
