I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_1.rpy", line 3457, in script call
    call lanaAcpt1 from _call_lanaAcpt1
  File "game/chapter_1.rpy", line 3516, in script call
    call lanaRjt2 from _call_lanaRjt2
  File "game/chapter_1.rpy", line 3921, in script call
    call ACCEPTEDLAW from _call_ACCEPTEDLAW
  File "game/chapter_1.rpy", line 1383, in script call
    call natsugropaccpt from _call_natsugropaccpt
  File "game/chapter_2.rpy", line 5441, in script
    kiara "Well if food is decent , we'll definitely come again"
Exception: Sayer 'kiara' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_1.rpy", line 3457, in script call
    call lanaAcpt1 from _call_lanaAcpt1
  File "game/chapter_1.rpy", line 3516, in script call
    call lanaRjt2 from _call_lanaRjt2
  File "game/chapter_1.rpy", line 3921, in script call
    call ACCEPTEDLAW from _call_ACCEPTEDLAW
  File "game/chapter_1.rpy", line 1383, in script call
    call natsugropaccpt from _call_natsugropaccpt
  File "game/chapter_2.rpy", line 5441, in script
    kiara "Well if food is decent , we'll definitely come again"
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'kiara' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
 0.2
Thu May 18 11:32:22 2023
